[versions]
junit-jupiter = "5.9.3"
assertj-core = "3.24.2"

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-core" }
